# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Installation'
  link: '/installation'
- label: 'Whats New'
  link: '/whats-new'
- label: 'Features'
  items:
    - label: 'Syntax Highlighting'
      link: '/features/syntax-highlighting'
    - label: 'Editor Features'
      link: '/features/editor'
    - label: 'Editor Plugins'
      link: '/features/plugins'
    - label: 'Examples'
      link: '/features/example'
- label: 'Contributing'
  items:
    - label: 'Project Structure'
      link: '/contributing/project-structure'
    - label: 'Supported Operations'
      link: '/contributing/operations'
