# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Installation'
  link: '/installation'
- label: 'Whats New'
  link: '/whats-new'
- label: 'Features'
  items:
    - label: 'Editor Features'
      link: '/features/editor'
    - label: 'Preferences'
      link: '/features/preferences'
    - label: 'Examples'
      link: '/features/example'
- label: 'Contributing'
  items:
    - label: 'Extending With Plugins'
      link: '/contributing/plugins'
    - label: 'Supported Operations'
      link: '/contributing/operations'
   
