# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Installation'
  link: '/gtkemu8086-docs/installation'
- label: 'Whats New'
  link: '/gtkemu8086-docs/whats-new'
- label: 'Features'
  items:
    - label: 'Syntax Highlighting'
      link: '/gtkemu8086-docs/features/syntax-highlighting'
    - label: 'Step'
      link: '/gtkemu8086-docs/features/step'
    - label: 'Examples'
      link: '/gtkemu8086-docs/features/example'
